#!/bin/bash
set -e

SWH_LAUNCHER_VERSION=2.6.3
{ command -v swh >/dev/null; } || { printf "ERROR: swh is not installed or is not executable.\nIt is suggested place swh in %s/bin and add\n  PATH=\$PATH:%s/bin\n  PATH\nto your .bashrc file.\n" "$PWD" "$HOME"; exit 1; }

## Example Application
# your app's special walkaround

prefix='example'							# give a unique name to your wineprefix
build='4.0'									# this is the dir name in cellar, provided by winehq or your own build.
install='/opt/wine-stable'					# '/opt/wine-stable', '/opt/wine-devel' or '/opt/wine-staging', used for store official winehq (on fedora or maybe your distro) to $cellar(default location is "$HOME/swh/cellar"). For your own built wine, copy it into $cellar
build_arch=win64							# win32 or win64. arch of your installed/built wine pagkage. when set to win64, you can create 32bit prefix by set WINEARCH=win32
export WINEARCH=win64								# win32 or win64. arch of your wineprefix. must export this variable

#invoker=""											# primusrun; perf recored
runner=wine											# wine, wine64, winedbg

#LC_ALL=zh_CN.utf8									# for non-unicode program, see 'locale -a' command

## DXVK setting (use with native d3dcompiler_47.dll ? https://github.com/doitsujin/dxvk/issues/875#issuecomment-456768012)
dxvk_install="$HOME/0_wine/dxvk/dxvk-0.96"						# extracted DXVK release archive here, support version 0.5x-0.9x, note winetricks can also install DXVK
#DXVK_HUD=1

#DXVK_CONFIG_FILE="$HOME/0_wine/DXVK_CONFIG/$prefix/dxvk.conf" 			# application configuration file
#DXVK_CONFIG_FILE="$HOME/0_wine/DXVK_CONFIG/amd/dxvk.conf" 				# tell dxvk you are using amd gpu
#DXVK_CONFIG_FILE="$HOME/0_wine/DXVK_CONFIG/nv/dxvk.conf" 				# tell dxvk you are using nvidia gpu
#export WINEDLLOVERRIDES="nvapi.dll,nvapi64.dll=d"

## FAudio setting
faudio_install="$HOME/0_wine/faudio/faudio-git-126cd0e"			# extract FAudio release archive here, build yourself or download https://github.com/Kron4ek/FAudio-Builds/releases

#XMODIFIERS='' 													# Unity Game Keyboard issue walkaround  https://www.gamingonlinux.com/articles/if-you-have-trouble-with-keyboard-input-in-some-unity-games-there-is-a-workaround.12411

# DIFFERENCE from normal indexed array in bash:
#   1. array[0] is reserved
#   2. valid subscript range [1-99] 
#   3. assign array members contiguously

dir[1]='C:\abc'
exe[1]='xyz.exe'
#args[1]=''

#dir[2]=""
#exe[2]=''
#args[2]=''

#dir[3]=""
#exe[3]=''
#args[3]=''

#dir[4]=""
#exe[4]=''
#args[4]=''

SWH_LAUNCHER="$0"
source swh "$@"
